# Generated by Django 5.2.6 on 2025-10-06 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=10)),
                ('texto', models.CharField(max_length=255)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=30)),
                ('numero', models.CharField(max_length=7)),
                ('bairro', models.CharField(max_length=40)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('complemento', models.CharField(max_length=30, null=True)),
                ('observacao', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Locatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=30)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorDiaria', models.FloatField()),
                ('descricao', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=50)),
                ('ofereceEntrega', models.BooleanField()),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.locador')),
            ],
        ),
        migrations.CreateModel(
            name='RequisicaoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateTimeField(auto_now_add=True)),
                ('dataConclusao', models.DateTimeField(null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.chat')),
                ('locatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.locatario')),
                ('ofertaLocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.ofertalocacao')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foiEntregue', models.BooleanField()),
                ('dataInicio', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
                ('dataConclusao', models.DateTimeField(null=True)),
                ('preco', models.FloatField()),
                ('frete', models.FloatField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.chat')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.endereco')),
                ('requisicaoLocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.requisicaolocacao')),
            ],
        ),
    ]
