# Generated by Django 5.2.6 on 2025-10-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='locacao',
            options={'verbose_name_plural': 'Locações'},
        ),
        migrations.AlterModelOptions(
            name='locador',
            options={'verbose_name_plural': 'Locadores'},
        ),
        migrations.AlterModelOptions(
            name='locatario',
            options={'verbose_name_plural': 'Locatários'},
        ),
        migrations.AlterModelOptions(
            name='ofertalocacao',
            options={'verbose_name_plural': 'Ofertas de Locação'},
        ),
        migrations.AlterModelOptions(
            name='requisicaolocacao',
            options={'verbose_name_plural': 'Requisição de Locação'},
        ),
        migrations.AddField(
            model_name='locacao',
            name='notaParaLocador',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='notaParaLocatario',
            field=models.IntegerField(null=True),
        ),
    ]
