# Generated by Django 5.2.6 on 2025-10-24 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0002_alter_chat_options_alter_endereco_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ofertalocacao',
            options={'ordering': ['-dataCriacao'], 'verbose_name_plural': 'Ofertas de Locação'},
        ),
        migrations.AddField(
            model_name='ofertalocacao',
            name='dataCriacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='locador',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='locador',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='user',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='ImagemOferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ofertas_imagens/')),
                ('ehImagemPrincipal', models.BooleanField(default=False)),
                ('ordem', models.IntegerField(default=0)),
                ('dataCriacao', models.DateTimeField(auto_now_add=True)),
                ('ofertaLocacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='AllugouApp.ofertalocacao')),
            ],
            options={
                'verbose_name': 'Imagem da Oferta',
                'verbose_name_plural': 'Imagens das Ofertas',
                'ordering': ['ordem', 'dataCriacao'],
            },
        ),
    ]
