# Generated by Django 5.2.6 on 2025-10-25 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0003_alter_ofertalocacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertalocacao',
            name='localizacao',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='AllugouApp.endereco'),
            preserve_default=False,
        ),
    ]
