# Generated by Django 5.2.6 on 2025-11-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0004_ofertalocacao_localizacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locador',
            name='senha',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='locatario',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
