# Generated by Django 5.2.6 on 2025-11-28 03:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0005_alter_locador_senha_alter_locatario_senha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='chat',
        ),
        migrations.AlterModelOptions(
            name='requisicaolocacao',
            options={'ordering': ['-dataCriacao'], 'verbose_name': 'Requisição de Locação', 'verbose_name_plural': 'Requisições de Locação'},
        ),
        migrations.RenameField(
            model_name='requisicaolocacao',
            old_name='dataInicio',
            new_name='dataCriacao',
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='dataInicioLocacao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='retiradaNoLocal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='valorFrete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requisicaolocacao',
            name='locatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='AllugouApp.locatario'),
        ),
        migrations.AlterField(
            model_name='requisicaolocacao',
            name='ofertaLocacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='AllugouApp.ofertalocacao'),
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(choices=[('locador', 'Locador'), ('locatario', 'Locatário')], max_length=10)),
                ('texto', models.TextField()),
                ('enviadoEm', models.DateTimeField(auto_now_add=True)),
                ('lido', models.BooleanField(default=False)),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='AllugouApp.requisicaolocacao')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['enviadoEm'],
            },
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
