# Generated by Django 5.2.6 on 2025-11-28 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0006_remove_locacao_chat_remove_requisicaolocacao_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaolocacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('concluida', 'Concluída')], default='pendente', max_length=10),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='vistoPeloLocador',
            field=models.BooleanField(default=False),
        ),
    ]
