# Generated by Django 5.2.6 on 2025-11-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0007_requisicaolocacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertalocacao',
            name='descricao',
            field=models.TextField(max_length=1500),
        ),
    ]
