# Generated by Django 5.2.6 on 2025-11-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0008_alter_ofertalocacao_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicaolocacao',
            name='dataConfirmacaoDevolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='dataConfirmacaoRecebimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='dataDevolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='dataFimLocacao',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='dataPagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='fotoDevolucao',
            field=models.ImageField(blank=True, null=True, upload_to='devolucoes/'),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='locadorConfirmouDevolucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='requisicaolocacao',
            name='locatarioConfirmouRecebimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='requisicaolocacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('paga', 'Paga'), ('em_uso', 'Em Uso'), ('devolvida', 'Devolvida'), ('concluida', 'Concluída')], default='pendente', max_length=10),
        ),
    ]
