# Generated by Django 5.2.6 on 2025-11-29 03:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0009_requisicaolocacao_dataconfirmacaodevolucao_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locacao',
            options={'ordering': ['-dataCriacao'], 'verbose_name': 'Locação', 'verbose_name_plural': 'Locações'},
        ),
        migrations.RenameField(
            model_name='locacao',
            old_name='dataInicio',
            new_name='dataCriacao',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='foiEntregue',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='frete',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='dataConclusao',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='dataConfirmacaoDevolucao',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='dataConfirmacaoRecebimento',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='dataDevolucao',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='dataPagamento',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='fotoDevolucao',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='locadorConfirmouDevolucao',
        ),
        migrations.RemoveField(
            model_name='requisicaolocacao',
            name='locatarioConfirmouRecebimento',
        ),
        migrations.AddField(
            model_name='locacao',
            name='comentarioParaLocador',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='comentarioParaLocatario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataConfirmacaoDevolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataConfirmacaoRecebimento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataDevolucao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataFimLocacao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataInicioLocacao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataPagamento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='enderecoEntrega',
            field=models.ForeignKey(blank=True, help_text='Endereço de entrega (se não for retirada)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='AllugouApp.endereco'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='fotoDevolucao',
            field=models.ImageField(blank=True, null=True, upload_to='devolucoes/'),
        ),
        migrations.AddField(
            model_name='locacao',
            name='locadorConfirmouDevolucao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locacao',
            name='locatarioConfirmouRecebimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locacao',
            name='retiradaNoLocal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('em_uso', 'Em Uso'), ('devolvida', 'Devolvida'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='ativa', max_length=10),
        ),
        migrations.AddField(
            model_name='locacao',
            name='valorFrete',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='locacao',
            name='valorTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locacao',
            name='dataConclusao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='notaParaLocador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='notaParaLocatario',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locacao',
            name='requisicaoLocacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locacao', to='AllugouApp.requisicaolocacao'),
        ),
        migrations.AlterField(
            model_name='requisicaolocacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada')], default='pendente', max_length=10),
        ),
    ]
