# Generated by Django 5.2.6 on 2025-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0010_alter_locacao_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='dataFimLocacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
