# Generated by Django 5.2.6 on 2025-11-29 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AllugouApp', '0011_alter_locacao_datafimlocacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locacao',
            name='dataFimLocacao',
        ),
        migrations.RemoveField(
            model_name='locacao',
            name='dataInicioLocacao',
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataFimPrevista',
            field=models.DateField(blank=True, help_text='Data de fim planejada (da requisição)', null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataFimReal',
            field=models.DateTimeField(blank=True, help_text='Quando o locador confirmou devolução', null=True),
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataInicioPrevista',
            field=models.DateField(default=django.utils.timezone.now, help_text='Data de início planejada (da requisição)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locacao',
            name='dataInicioReal',
            field=models.DateTimeField(blank=True, help_text='Quando o locatário confirmou recebimento', null=True),
        ),
    ]
